spring.config.import: optional:file:.env[.properties]


spring:
  application:
    name: springdev



  datasource:
    url: jdbc:mysql://localhost:3306/production-spring-db
    username: root   # replace with your PostgreSQL username
    password: Aman@1234   # replace with your PostgreSQL password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  spring:
    security:
      oauth2:
        client:
          registration:
            google:
              client-id: ${GOOGLE_CLIENT_ID}
              client-secret: ${GOOGLE_CLIENT_SECRET}


#  security:
#    user:
#      name : aman
#      password : pass



jwt:
  secretKey : ${JWT_SECRET_KEY}

