spring:
  application:
    name: springdev



  datasource:
    url: jdbc:mysql://localhost:3306/production-spring-db
    username: root   # replace with your PostgreSQL username
    password: Aman@1234   # replace with your PostgreSQL password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


#  security:
#    user:
#      name : aman
#      password : pass



jwt:
  secretKey : h34b5h4b545JHBNSDFVJHB3U4HBL3IHJ4BT3Btb45ty34btrb3478b

